"""empty message

Revision ID: 1c7a6f48e6d5
Revises: 10158aa25df5
Create Date: 2022-11-04 14:23:37.257044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c7a6f48e6d5'
down_revision = '10158aa25df5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('name', sa.String(length=25), nullable=False))
    op.add_column('User', sa.Column('user_name', sa.String(length=25), nullable=False))
    op.add_column('User', sa.Column('banner', sa.String(length=500), nullable=False))
    op.add_column('User', sa.Column('profile_photo', sa.String(length=500), nullable=False))
    op.add_column('User', sa.Column('bio', sa.String(length=250), nullable=False))
    op.add_column('User', sa.Column('following', sa.Integer(), nullable=False))
    op.add_column('User', sa.Column('followers', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'followers')
    op.drop_column('User', 'following')
    op.drop_column('User', 'bio')
    op.drop_column('User', 'profile_photo')
    op.drop_column('User', 'banner')
    op.drop_column('User', 'user_name')
    op.drop_column('User', 'name')
    # ### end Alembic commands ###
