"""empty message

Revision ID: 4d4eddd4f248
Revises: 1e036e806401
Create Date: 2022-11-04 15:14:43.562475

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4d4eddd4f248'
down_revision = '1e036e806401'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('User', 'banner',
               existing_type=mysql.VARCHAR(length=500),
               nullable=True)
    op.alter_column('User', 'profile_photo',
               existing_type=mysql.VARCHAR(length=500),
               nullable=True)
    op.alter_column('User', 'bio',
               existing_type=mysql.VARCHAR(length=250),
               nullable=True)
    op.alter_column('User', 'following',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('User', 'followers',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('User', 'followers',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('User', 'following',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('User', 'bio',
               existing_type=mysql.VARCHAR(length=250),
               nullable=False)
    op.alter_column('User', 'profile_photo',
               existing_type=mysql.VARCHAR(length=500),
               nullable=False)
    op.alter_column('User', 'banner',
               existing_type=mysql.VARCHAR(length=500),
               nullable=False)
    # ### end Alembic commands ###
