"""empty message

Revision ID: f1f3913c716c
Revises: d86ce5ba4454
Create Date: 2022-10-27 21:56:09.595594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1f3913c716c'
down_revision = 'd86ce5ba4454'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Posts', sa.Column('headline', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Posts', 'headline')
    # ### end Alembic commands ###
